### PR TITLE
Fix rnaturalearth install error

### PR DESCRIPTION
**Pull request by bpbond**
Based on https://philmikejones.me/tutorials/2018-08-29-install-sf-ubuntu.html

### CODE REVIEW

**Comment by bpbond** [comment]
@kendalynnm I have fixed the yaml problem, but the RMarkdown is still erroring because of something else — I looked, and the new TEMPEST prediction code is the problem. This occurs on my local system as well. Over to you to fix :)

**Comment by kendalynnm** [comment]
Got it, this is because the big GeoTiff files don't exist within the GitHub repo (assuming I'm using that lingo correctly). Maybe we should make it so that the soil grids data is all 1's in the tiffs aren't present? With a big neon warning sign? That would fix the render problem.

**Comment by bpbond** [comment]
> Maybe we should make it so that the soil grids data is all 1's if the tiffs aren't present? With a big neon warning sign? 

That's what we do already:
```r
  # geoTIFF files are not present
  # issue a warning
  warning("geoTIFF files are not present! Analysis will not be correct")
  meta_df$sg_clay <- 1
  meta_df$sg_ocs <- 1
```

**Review by kendalynnm — APPROVED** [review]
This all looks good to me, thanks!

**Comment by bpbond** [comment]
Hurray! OK, merge when ready, and then you can update #64 and make sure _that_ test runs (it should).

**Pull request merged**
